# Generated by Django 4.2 on 2023-04-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sil_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sil_user.course'),
        ),
    ]
